# Generated by Django 5.2.1 on 2025-06-05 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Faktúra'), ('contract', 'Zmluva'), ('receipt', 'Pokladničný doklad'), ('other', 'Iný')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
